name: sample_sheet_location
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2
  easy_localization_generator: ^0.3.2
  csv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9
  freezed: ^2.5.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.4.0

dependency_overrides:
  csv: ^5.1.1
  intl: ^0.18.1

flutter:

  uses-material-design: true

  assets:
    - assets/localization/

flutter_gen:
    output: lib/common/gen


